### ISSUE TITLE
pattern in html is build wrong to the production

### ISSUE THREAD

**Issue by grauschnabel** [mgechev/angular2-seed#1283]
Hi there

I have a template which contains:

 ```
<input autofocus="autofocus" class="form-control" placeholder="Email" type="email"
	     id="email" [(ngModel)]="model.email" name="email" required
             pattern="^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$"
	     #email="ngModel"/>

```
in dev it works fine, but when doing 

`npm run build.prod`

the pattern is changed to
`^w+([.-]?w+)*@w+([.-]?w+)*(.w{2,3})+$`
you see the missing \ in the string.  (i found this out with the firefox inspector)
so the production code is not working.

How can this be fixed, and where in the build.prod will this be produced?

Thanks,
Martin

**Comment by mgechev** [comment]
Does your production build runs the ahead of time compiler (compile.ahead.prod gulp task)?

**Comment by grauschnabel** [comment]
Seems to be fixed in the new rc6 from yesterday... Thanks.

**Comment by grauschnabel** [comment]
it is now there again.  i merged today the angular2-seed tree to my project.
the build.prod creates the error, build.prod.ext failes with
```
[13:55:55] 'compile.ahead.prod' errored after 2.24 s                                  
r.rb:38:in `call'                                                                    │[13:55:55] TypeError: Cannot read property 'push' of undefined                        
        from /home/martin/.gem/ruby/2.3.0/gems/spring-1.7.2/lib/spring/application.rb│    at /home/martin/Projects/lf/client/tools/tasks/seed/compile.ahead.prod.ts:26:17 

```

what can I do?

**Comment by TheDonDope** [comment]
Hi @grauschnabel,

have you thought about using a programmatic validator to enforce your email pattern?

Have a look here: http://blog.thoughtram.io/angular/2016/03/14/custom-validators-in-angular-2.html#building-a-custom-validator

**Comment by grauschnabel** [comment]
Yes, but normally I go the easiest way- and in development it works well, I just want the same in production...

**Comment by sasikumardr** [comment]
Known issue in [gulp-inline-ng2-template](https://github.com/ludohenin/gulp-inline-ng2-template/issues/50)

**Comment by mgechev** [comment]
Currently `build.prod.exp` doesn't use `gulp-inline-ng2-template` because it uses AoT with `@angular/compiler`.

I'll take a look at this issue as soon as I can. If anyone has some spare time help will be greatly appreciated!

**Comment by jpinkster** [comment]
I am also experiencing this issue when trying to run a pattern check inside my template. It is striping out the \.

For now I have moved my RegExp to the controller but would love to continue to leverage this functionality once we figure out where this issue is coming from!

**Comment by mgechev** [comment]
@grauschnabel I can no longer reproduce the issue using `npm run build.prod.exp`. I did some fixes in the AoT compilation support so I think everything should work now.

Would you verify and close the issue?

**Comment by mgechev** [comment]
Closing it due to inactivity. @grauschnabel let me know if the issue is not resolved yet.

**Comment by Flood** [comment]
I am still experiencing the issue. Now in scss files (I guess they are minified as well) "content: '\24'" is compiled to "content: '24'" (the backslash is gone).
