### ISSUE TITLE
Error in Safari Version 8.0.7 (10600.7.12)

### ISSUE THREAD

**Issue by jneveux** [mgechev/angular2-seed#43]
Hi all,

I'm getting the following error in Safari Version 8.0.7 (10600.7.12), everything works fine in FireFox/Chrome latest version:
```
[Error] TypeError: undefined is not a function (evaluating '$__2.next()')

from@http://localhost:5555/lib/traceur-runtime.js?v=0.0.0:2717:102
values@http://localhost:5555/lib/angular2.js?v=0.0.0:4710:30
_createListOfBindings@http://localhost:5555/lib/angular2.js?v=0.0.0:23646:29
resolve@http://localhost:5555/lib/angular2.js?v=0.0.0:24265:41
resolveAndCreate@http://localhost:5555/lib/angular2.js?v=0.0.0:24269:52
_createAppInjector@http://localhost:5555/lib/angular2.js?v=0.0.0:26476:48
http://localhost:5555/lib/angular2.js?v=0.0.0:26457:43
run@http://localhost:5555/lib/zone.js?v=0.0.0:113:22
http://localhost:5555/lib/angular2.js?v=0.0.0:10596:43
run@http://localhost:5555/lib/angular2.js?v=0.0.0:10563:41
bootstrap@http://localhost:5555/lib/angular2.js?v=0.0.0:26456:13
http://localhost:5555/:37:21
global code@http://localhost:5555/:40:8
appendChild@[native code]
doEval@http://localhost:5555/lib/system.src.js?v=0.0.0:2347:23
__eval@http://localhost:5555/lib/system.src.js?v=0.0.0:2317:13
exec@http://localhost:5555/lib/system.src.js?v=0.0.0:339:11
execute@http://localhost:5555/lib/system.src.js?v=0.0.0:1222:22
linkDynamicModule@http://localhost:5555/lib/system.src.js?v=0.0.0:669:36
link@http://localhost:5555/lib/system.src.js?v=0.0.0:528:28
execute@http://localhost:5555/lib/system.src.js?v=0.0.0:852:15
o@http://localhost:5555/lib/es6-module-loader-sans-promises.js?v=0.0.0:7:7021
p@http://localhost:5555/lib/es6-module-loader-sans-promises.js?v=0.0.0:7:7387
j@http://localhost:5555/lib/es6-module-loader-sans-promises.js?v=0.0.0:7:4933
k@http://localhost:5555/lib/es6-module-loader-sans-promises.js?v=0.0.0:7:5318
http://localhost:5555/lib/es6-module-loader-sans-promises.js?v=0.0.0:7:5509
run@http://localhost:5555/lib/zone.js?v=0.0.0:113:22
zoneBoundFn@http://localhost:5555/lib/zone.js?v=0.0.0:86:22
PromiseResolutionHandlerFunction@[native code]
	logError (angular2.js, line 17329)
	defaultErrorReporter (angular2.js, line 26442)
	_onError (angular2.js, line 10639)
	onError (angular2.js, line 10582)
	run (zone.js, line 116)
	(anonymous function) (angular2.js, line 10596)
	run (angular2.js, line 10563)
	bootstrap (angular2.js, line 26456)
	(anonymous function) (localhost, line 37)
	global code (localhost, line 40)
	appendChild ([native code], line 0)
	doEval (system.src.js, line 2347)
	__eval (system.src.js, line 2317)
	exec (system.src.js, line 339)
	execute (system.src.js, line 1222)
	linkDynamicModule (system.src.js, line 669)
	link (system.src.js, line 528)
	execute (system.src.js, line 852)
	o (es6-module-loader-sans-promises.js, line 7)
	p (es6-module-loader-sans-promises.js, line 7)
	j (es6-module-loader-sans-promises.js, line 7)
	k (es6-module-loader-sans-promises.js, line 7)
	(anonymous function) (es6-module-loader-sans-promises.js, line 7)
	run (zone.js, line 113)
	zoneBoundFn (zone.js, line 86)
	PromiseResolutionHandlerFunction ([native code], line 0)
[Error] TypeError: undefined is not a function (evaluating '$__2.next()')
	(anonymous function) (angular2.js, line 10609)
	run (angular2.js, line 10563)
	bootstrap (angular2.js, line 26456)
	(anonymous function) (localhost, line 37)
	global code (localhost, line 40)
	appendChild ([native code], line 0)
	doEval (system.src.js, line 2347)
	__eval (system.src.js, line 2317)
	exec (system.src.js, line 339)
	execute (system.src.js, line 1222)
	linkDynamicModule (system.src.js, line 669)
	link (system.src.js, line 528)
	execute (system.src.js, line 852)
	o (es6-module-loader-sans-promises.js, line 7)
	p (es6-module-loader-sans-promises.js, line 7)
	j (es6-module-loader-sans-promises.js, line 7)
	k (es6-module-loader-sans-promises.js, line 7)
	(anonymous function) (es6-module-loader-sans-promises.js, line 7)
	run (zone.js, line 113)
	zoneBoundFn (zone.js, line 86)
	PromiseResolutionHandlerFunction ([native code], line 0)
[Error] Error loading "app" at http://localhost:5555/app.js?v=0.0.0
Error evaluating http://localhost:5555/app.js?v=0.0.0
TypeError: undefined is not a function (evaluating '$__2.next()') Report this error at https://github.com/mgechev/angular2-seed/issues
	(anonymous function) (init.js, line 6)
	run (zone.js, line 113)
	zoneBoundFn (zone.js, line 86)
	run (zone.js, line 113)
	zoneBoundFn (zone.js, line 86)
```

Thanks,

Jean

**Comment by mgechev** [comment]
I'll add it to my schedule for tomorrow/early next week.

**Comment by vellengs** [comment]
same issue on  Safari Version 8.0.6

**Comment by mgechev** [comment]
Safari doesn't implement `next` in `MapIterator`, which causes traceur to throw this error.

The issue is addressed [here](https://github.com/angular/angular/pull/3389).

**Comment by tmclane** [comment]
Can anyone confirm it works/doesn't work for them now?  I am still having the same error unless I go back to the beta 28 commit.

**Comment by mgechev** [comment]
I will take a look tomorrow.
